site_name: Helper CLI Docs
site_author: Nguyen Huy
site_description: Helper CLI Docs
site_url: https://helper.huyab.click
repo_url: https://github.com/nguyenhuy158/helper
# theme: readthedocs
# theme: material
theme:
    # name: mkdocs
    name: material
    font:
        text: Be Vietnam Pro
        code: Roboto Mono
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
docs_dir: src_docs
site_dir: docs

markdown_extensions:
    - attr_list
    - mkdocs-click
    # - smarty
    # - toc:
    #       permalink: true

plugins:
    - minify
    - rss
    # - git-authors
    - search:
          lang: en

watch:
    - helper

nav:
    - Home: index.md
    - About: about.md
