[project]
name = "helper-cli"
dynamic = ["version"]
description = "Simple system info CLI"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-3.0-or-later" }
authors = [
    { name = "Huy Nguyen", email = "huy.ntq02@gmail.com" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent"
]
dependencies = [
    "click>=8.0.0",
    "speedtest-cli>=2.1.0",
    "psutil>=5.0.0",
    "pyyaml>=6.0",
    "tabulate>=0.9.0",
    "rich>=13.0.0"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0",
    "pytest>=7.0.0",
    "pytest-mock>=3.0.0",
    "watchdog>=2.0.0"
]

[project.urls]
Homepage = "https://github.com/nguyenhuy158/helper"
Repository = "https://github.com/nguyenhuy158/helper"

[project.scripts]
helper = "helper.main:cli"
h = "helper.main:cli"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {file = ["VERSION"]}

[tool.ruff]
line-length = 100
extend-exclude = ["tools"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP", "B", "SIM"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
